#Github CI File
name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Manual Run
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
  
  runCommands:
      runs-on: self-hosted
      #Sequential run
      needs: build
      steps:
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  
  Slack_notify:
      runs-on: self-hosted
      if: always()
      needs: [build,runCommands]
      steps:
      - uses: actions/checkout@v2
      - name: Slack Notifications
        uses: rtcamp/action-slack-notify@master
        env:
           SLACK_WEBHOOK: $ {{secrets.SLACK_WEBHOOK}}
           SLACK_TITLE: Slack Notifications
           SLACK_USERNAME: SLACK BOT
           SLACK_MESSAGE: Triggered by Github Actions 1) build ${{needs.build.result}} 2) runCommands ${{needs.runCommands.result}}
