#Github CI File
name: CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Manual Run
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
  
  runCommands:
      runs-on: self-hosted
      #Sequential run
      needs: build
      steps:
      - name: Run a multi-line script
        env: 
          test: ${{ secrets.test }} 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo $test
          
  
 
